### ISSUE TITLE
Section 5 appendix

### ISSUE THREAD

**Issue by truizbon** [KeyserSoze01/Team14#9]
Appendix A, B, C in SRS

**Comment by KeyserSoze01** [comment]
Section 5

    Other Requirements

        1. Performance should be fast. Page should take no longer than 2s to load.
        2. Site should be secure. SSL certificate is required. No domain that is not HTTPS.
        3. Compliance. Only legitimate and legal books will be sold. No counterfits or rebranding.
        4. Maintenance will be done on a regular schedule to ensure site security and usability.
        5. Site can be used locally by being automatically tranlated into appropriate languages.
